import type { ApiOpportunity } from './apiClient';
import type { Opportunity } from '@/data/mockData';

const JOURNEY_TO_TYPE: Record<ApiOpportunity['journey'], Opportunity['type']> = {
  public_procurement: 'public',
  tender: 'private',
  subcontracting: 'subcontracting',
};

function toDisplayStatus(apiStatus: string): Opportunity['status'] {
  switch (apiStatus) {
    case 'classified':
      return 'En cours';
    case 'submitted':
      return 'Déposé';
    case 'awarded':
      return 'Gagné';
    case 'lost':
      return 'Perdu';
    default:
      return 'Non analysé';
  }
}

function formatAmount(value: number | null, currency: string | null): string {
  if (value === null || value === undefined) return 'Montant non communiqué';
  return new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 0 }).format(value) + ' ' + (currency || 'EUR');
}

function formatDeadline(value: string | null): string {
  // Deliberately NOT pre-formatted into a display string here. Every
  // consumer of Opportunity.deadline (OpportunityListCard's days-remaining
  // countdown, RecherchePage, OpportunityJourneyPage, TableauDeBordPage,
  // use-mission, etc.) does its own `new Date(o.deadline)` - either for a
  // days-left computation or its own toLocaleDateString() call - matching
  // the raw-ISO-string contract on the Opportunity type (see mockData.ts).
  // A previous pass here pre-formatted this into a French display string
  // ("15 sept. 2026"), which every one of those call sites then re-parsed
  // with `new Date(...)` - an unparseable string, so days-remaining always
  // came out as NaN/0 and re-formatted dates broke. Pass the raw ISO
  // timestamp straight through instead; nothing in the codebase renders
  // this field unwrapped, so there's no literal-ISO-string display bug to
  // guard against.
  return value || '';
}

export function apiOpportunityToDisplay(api: ApiOpportunity): Opportunity {
  return {
    id: api.id,
    title: api.title,
    // Buyer/organization name now comes straight from the API (see
    // marchesdirect-backend's opportunities.buyer_name), populated for
    // BOAMP-sourced records and demo/seed data. Still blank for
    // sources that don't expose it (TED, some PLACE records).
    organization: api.buyer_name || '',
    location: [api.location_city, api.location_region].filter(Boolean).join(', '),
    department: api.location_department || '',
    distance: '',
    amount: formatAmount(api.estimated_value, api.currency),
    // Raw ISO timestamp straight from the API (see formatDeadline above for
    // why this isn't pre-formatted into a display string here).
    deadline: formatDeadline(api.deadline),
    status: toDisplayStatus(api.ai_classification_status),
    match: api.match_score ?? 0,
    type: JOURNEY_TO_TYPE[api.journey],
    sector: api.trade_name || '',
    saved: false,
    published: api.publication_date || undefined,
    // Client's explicit ask (WhatsApp): raw government notice text is
    // "très brute et peu lisible" - prefer the AI-restructured summary
    // (already generated by jobs/aiProcessing.ts, just never read here)
    // over the untouched source description. Falls back to raw text only
    // while a freshly-ingested listing is still waiting in that job's
    // queue (ai_summary null) - better a rough description than a blank
    // card, but it's the exception, not the default, once classification
    // catches up.
    description: api.ai_summary || api.description || undefined,
    identityUnlocked: api.identity_unlocked,
  };
}
