import type { ApiOpportunity } from './apiClient';
import type { Opportunity } from '@/data/mockData';

const JOURNEY_TO_TYPE: Record<ApiOpportunity['journey'], Opportunity['type']> = {
  public_procurement: 'public',
  tender: 'private',
  subcontracting: 'subcontracting',
};

function toDisplayStatus(apiStatus: string): Opportunity['status'] {
  switch (apiStatus) {
    case 'classified':
      return 'En cours';
    case 'submitted':
      return 'Déposé';
    case 'awarded':
      return 'Gagné';
    case 'lost':
      return 'Perdu';
    default:
      return 'Non analysé';
  }
}

function formatAmount(value: number | null, currency: string | null): string {
  if (value === null || value === undefined) return 'Montant non communiqué';
  return new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 0 }).format(value) + ' ' + (currency || 'EUR');
}

function formatDeadline(value: string | null): string {
  if (!value) return '';
  const d = new Date(value);
  if (isNaN(d.getTime())) return '';
  return d.toLocaleDateString('fr-FR', { day: 'numeric', month: 'short', year: 'numeric' });
}

export function apiOpportunityToDisplay(api: ApiOpportunity): Opportunity {
  return {
    id: api.id,
    title: api.title,
    // Buyer/organization name now comes straight from the API (see
    // marchesdirect-backend's opportunities.buyer_name), populated for
    // BOAMP-sourced records and demo/seed data. Still blank for
    // sources that don't expose it (TED, some PLACE records).
    organization: api.buyer_name || '',
    location: [api.location_city, api.location_region].filter(Boolean).join(', '),
    department: api.location_department || '',
    distance: '',
    amount: formatAmount(api.estimated_value, api.currency),
    // api.deadline is a raw ISO timestamp (e.g. "2026-08-28T16:00:00.000Z")
    // straight from Postgres - every card that rendered `{o.deadline}`
    // directly was showing that literal string to visitors instead of a
    // readable date. Formatted once here so every card/page using this
    // adapter gets it fixed, rather than patching each page's JSX.
    deadline: formatDeadline(api.deadline),
    status: toDisplayStatus(api.ai_classification_status),
    match: api.match_score ?? 0,
    type: JOURNEY_TO_TYPE[api.journey],
    sector: api.trade_name || '',
    saved: false,
    published: api.publication_date || undefined,
    // Client's explicit ask (WhatsApp): raw government notice text is
    // "très brute et peu lisible" - prefer the AI-restructured summary
    // (already generated by jobs/aiProcessing.ts, just never read here)
    // over the untouched source description. Falls back to raw text only
    // while a freshly-ingested listing is still waiting in that job's
    // queue (ai_summary null) - better a rough description than a blank
    // card, but it's the exception, not the default, once classification
    // catches up.
    description: api.ai_summary || api.description || undefined,
    identityUnlocked: api.identity_unlocked,
  };
}
