import { chromium, devices } from 'playwright';
const browser = await chromium.launch();
const context = await browser.newContext({ ...devices['Pixel 5'] });
const page = await context.newPage();
await page.goto('http://localhost:4173/', { waitUntil: 'networkidle' });
await page.waitForTimeout(1000);
await page.locator('svg.rsm-svg').first().scrollIntoViewIfNeeded();
await page.waitForTimeout(300);
const html = await page.evaluate(() => document.querySelector('svg.rsm-svg')?.outerHTML.slice(0, 1500));
console.log(html);
await browser.close();
