import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 480, height: 1200 } });
await page.goto('file:///home/claude/prototype-fix/marches-direct-parcours-corrige-v2.html', { waitUntil: 'networkidle' });
await page.waitForTimeout(400);
await page.click("button:has-text('Appel d’offres')").catch(async()=>{await page.click("text=Appel");});
await page.waitForTimeout(300);
await page.click('text=Mémoire');
await page.waitForTimeout(300);
await page.screenshot({ path: '/tmp/regress_private_memoire_level1.png', fullPage: true });
await browser.close();
