import React, { createContext, useContext, useState } from 'react';

type Lang = 'fr' | 'en';
type Translations = Record<string, string | string[]>;

const frTranslations: Translations = {
  // Nav
  home: 'Accueil',
  tenders: "Appels d'offres",
  public: 'Marchés publics',
  subcontracting: 'Sous-traitance',
  howItWorks: 'Comment ça marche',
  pricing: 'Tarifs',
  search: 'Recherche',
  dashboard: 'Tableau de bord',
  profile: 'Profil',
  contact: 'Contact',
  // Hero
  heroLine1: 'Votre prochaine opportunité',
  heroLine2: 'commence ici.',
  heroSub: "Choisissez votre parcours ou échangez avec un conseiller Marchés Direct.",
  bookAppointment: 'Prendre rendez‑vous',
  callBack: 'Être rappelé',
  // Sections
  whoWeAre: 'Qui sommes-nous ?',
  whoWeAreSub: "Une équipe experte à vos côtés, jusqu'à la signature de vos premiers marchés.",
  discoverUs: 'Découvrir Marchés Direct →',
  nearYou: 'PRÈS DE CHEZ VOUS',
  opportunitiesFrance: 'Des opportunités partout en France.',
  exploreFrance: 'Explorez les marchés par région, département ou grande ville.',
  seeAllZones: 'Voir toutes les zones',
  regions: 'Régions',
  departments: 'Départements',
  cities: 'Villes',
  mapSearchRegion: 'Rechercher une région',
  mapSearchDepartment: 'Rechercher un département ou un code',
  mapSearchCity: 'Rechercher une ville',
  mapTouchRegion: 'Touchez une région ou zoomez sur la carte',
  mapTouchDepartment: 'Touchez un département ou zoomez sur la carte',
  mapTouchCity: 'Recherchez une ville, puis validez',
  mapViewOpportunitiesIn: 'Voir les opportunités en',
  mapViewOpportunitiesAround: 'Voir les opportunités autour de',
  mapSelectPrompt: 'Sélectionnez une zone',
  mapSelectPromptSub: 'Touchez une région, un département ou recherchez une ville pour voir les opportunités disponibles.',
  mapOpportunitiesCount: 'opportunités',
  mapNoData: 'Aucune opportunité recensée pour le moment.',
  mapCitySearchButton: 'Afficher',
  international: 'Opportunités à l\'international',
  internationalSub: 'Accédez également aux marchés disponibles hors de France.',
  sectors: 'Secteurs d\'activité',
  sectorsSub: 'Des opportunités pour tous les métiers.',
  sectorsSub2: 'Explorez les secteurs et accédez aux opportunités adaptées à votre activité.',
  seeAllSectors: 'Voir tous les secteurs',
  news: 'Actualités',
  newsSub: "L'actualité des marchés.",
  newsSub2: 'Réglementation, nouvelles opportunités et secteurs à suivre.',
  seeAllNews: 'Voir toutes les actualités',
  finalCtaHeading: 'Besoin d\'aide pour trouver la bonne opportunité ?',
  finalCtaSub: "Un conseiller Marchés Direct vous aide à identifier le parcours adapté à votre entreprise.",
  // Footer
  copyright: '© 2026 MarchesDirect',
  legalNotice: 'Mentions légales',
  privacy: 'Confidentialité',
  terms: 'CGU',
  footerBrand: 'Marchés Direct',
  footerMarkets: 'Marchés',
  footerExplore: 'Explorer',
  footerLegal: 'Légal',
  footerTagline: "La plateforme de mise en relation pour les marchés publics, appels d'offres privés et la sous-traitance.",
  footerAbout: 'À propos',
  footerTeam: 'Notre équipe',
  footerZones: 'Zones géographiques',
  footerSectors: "Secteurs d'activité",
  footerFaq: 'FAQ',
  // Modals
  appointmentTitle: 'Prendre rendez‑vous',
  callbackTitle: 'Être rappelé',
  callbackName: 'Nom',
  callbackCompany: 'Entreprise',
  callbackPhone: 'Téléphone',
  callbackTime: 'Moment souhaité',
  callbackSubmit: 'Demander un rappel',
  callbackConfirm: 'Votre demande a bien été envoyée. Nous vous rappelons rapidement.',
  // Steps
  step1: 'On surveille',
  step2: 'On trie & qualifie',
  step3: 'On prépare',
  step4: 'Vous validez',
  step5: 'On dépose',
  step6: 'On vous accompagne',
  // Bottom nav labels
  navHome: 'Accueil',
  navSearch: 'Recherche',
  navDashboard: 'Tableau de bord',
  navProfile: 'Profil',
  
  // Zone Page
  zoneBreadcrumbHome: 'Accueil',
  zoneBreadcrumbSectors: 'Secteurs',
  zoneBreadcrumbConstruction: 'Travaux & construction',
  zoneTitleLine1: 'Travaux &',
  zoneTitleLine2: 'construction',
  zoneSubLine1: 'Quel type d’opportunité recherchez-vous dans ce secteur ?',
  zoneSubLine2: 'Votre choix sera conservé pour la suite du parcours.',
  zoneCardPublicTitle: 'Marchés publics',
  zoneCardPublicDesc: 'Travaux commandés par les collectivités et établissements publics.',
  zoneCardPrivateTitle: 'Appels d’offres privés',
  zoneCardPrivateDesc: 'Projets de promoteurs, entreprises et donneurs d’ordre privés.',
  zoneCardSubTitle: 'Sous-traitance',
  zoneCardSubDesc: 'Trouvez un chantier, une mission ou un partenaire.',
  changeSector: 'Changer de secteur',
  selectedSectorLabel: 'Secteur sélectionné :',
  selectedSectorValue: 'Travaux & construction',

  // Search Page
  searchHeaderTag: 'Je suis sous-traitant',
  searchHeaderTitle: 'Trouvez des chantiers adaptés à votre entreprise.',
  searchHeaderSub: 'Des besoins de sous-traitance qualifiés selon votre métier, votre zone et vos disponibilités.',
  searchKeywords: 'Mots-clés',
  searchKeywordsPlaceholder: 'Ex. peinture, électricité, gros œuvre...',
  searchLocation: 'Localisation',
  searchLocationPlaceholder: 'Ville ou département',
  searchRadius: 'Rayon',
  searchAvailability: 'Disponibilité',
  searchAvailabilityNow: 'Dès maintenant',
  searchAvailability1: 'Sous 1 mois',
  searchAvailability3: 'Sous 3 mois',
  searchButton: 'Rechercher',
  searchResults: 'missions compatibles',
  searchNew: 'Nouveau',
  searchStart: 'Démarrage',
  searchDuration: 'Durée',
  searchBudget: 'Budget indicatif',
  searchCompatible: 'Profil recherché compatible',
  searchView: 'Voir la mission',

  // Generic
  all: 'Tous',
  allF: 'Toutes',
  sortRecent: 'Trier : Plus récents',
  sortMatch: 'Trier : Meilleur match',
  sortDeadline: 'Trier : Échéance proche',

  // Appels Page
  appelsTag: 'Marchés privés',
  appelsTitle: "Appels d'offres",
  appelsSub: 'Promoteurs, bailleurs et grandes entreprises. Contact direct et réactivité avant tout.',
  appelsLocation: 'Localisation',
  appelsLocationPlaceholder: 'Ville, département...',
  appelsSector: 'Secteur',
  appelsCategory: 'Catégorie',
  appelsReset: 'Réinitialiser',
  appelsFilters: 'Filtres',
  appelsResults: 'résultat',
  appelsResultsPlural: 'résultats',
  appelsNoResults: 'Aucun résultat',
  appelsNoResultsSub: 'Aucune opportunité ne correspond à ces filtres pour le moment. Essayez d\'élargir votre rayon ou de changer de métier.',
  appelsResetFilters: 'Réinitialiser les filtres',

  // Public Page
  publicTag: 'BOAMP · PLACE · JOUE',
  publicTitle: 'Marchés publics',
  publicSub: 'Mairies, État, collectivités. Conformité, pièces du DCE et mémoire technique générés pour vous.',
  publicStatus: 'Statut',
  publicResults: 'opportunité trouvée',
  publicResultsPlural: 'opportunités trouvées',
  publicNoResults: 'Aucun résultat',
  publicNoResultsSub: 'Aucune opportunité ne correspond à ces filtres pour le moment. Essayez d\'élargir votre rayon ou de changer de métier.',
  publicResetFilters: 'Réinitialiser les filtres',

  // Subcontracting Page
  subTag: 'Entre entreprises',
  subTitle: 'Sous-traitance',
  subSub: 'Lots à reprendre entre entreprises du bâtiment. Rapidité et disponibilité en priorité.',
  subModeChantier: 'Je cherche un chantier',
  subModePartenaire: 'Je cherche un partenaire',
  subDept: 'Département',
  subJob: 'Métier',
  subLocationPlaceholder: 'Ville...',
  subResults: 'lot disponible',
  subResultsPlural: 'lots disponibles',
  subNoResults: 'Aucun résultat',
  subNoResultsSub: 'Aucune opportunité ne correspond à ces filtres.',
  subResetFilters: 'Réinitialiser les filtres',

  // Steps Page - Descriptions
  stepsTitle: "De l'opportunité à la signature.",
  stepsSub: 'Un parcours simple, clair et accompagné.',
  step1Desc: 'Nos sources collectent les opportunités publiques et privées.',
  step2Desc: 'Chaque opportunité est classée selon votre activité et vos critères.',
  step3Desc: 'Nous constituons le dossier administratif et technique.',
  step4Desc: 'Vous vérifiez et ajustez les éléments avant envoi.',
  step5Desc: 'Le dossier est transmis sur la plateforme concernée.',
  step6Desc: 'Nous restons à vos côtés jusqu’à la signature.',
  stepsCtaTitle: "Besoin d'un accompagnement personnalisé ?",
  stepsCtaAbout: 'À propos →',
  stepsCtaTeam: 'Notre équipe →',
  stepsCtaFaq: 'Questions fréquentes →',

  // Pricing Page
  pricingTitle: 'Un abonnement, toutes vos opportunités.',
  pricingSub: 'Commencez gratuitement. Un conseiller vous rappelle pour configurer votre profil et choisir la formule adaptée.',
  pricingNote: "Tous les tarifs s'entendent HT. Sans engagement. Résiliation à tout moment depuis votre espace profil.",
  planDiscoveryName: 'DÉCOUVERTE',
  planDiscoveryPeriod: "14 jours d'essai",
  planDiscoveryFeat1: '1 métier suivi',
  planDiscoveryFeat2: 'Alertes par email',
  planDiscoveryFeat3: 'Recherche et filtres',
  planDiscoveryFeat4: 'Support par email',
  planDiscoveryCta: 'Essayer gratuitement',
  planProName: 'PRO',
  planProPeriod: '/ mois',
  planProBadge: 'Le plus choisi',
  planProFeat1: 'Métiers et journeys illimités',
  planProFeat2: 'Matching et résumé IA',
  planProFeat3: 'Chatbot IA',
  planProFeat4: 'Module réponse aux appels d\'offres',
  planProFeat5: 'Profil entreprise et coffre-fort documentaire',
  planProCta: 'Demander un rappel',
  planEntName: 'ENTREPRISE',
  planEntPrice: 'Sur devis',
  planEntPeriod: 'Plusieurs utilisateurs',
  planEntFeat1: 'Comptes multi-utilisateurs',
  planEntFeat2: 'Export CRM dédié',
  planEntFeat3: 'Accompagnement dédié',
  planEntFeat4: 'MFA et rôles avancés',
  planEntCta: 'Être rappelé',

  // À propos Page
  aboutTag: 'À propos',
  aboutTitle: 'Marchés Direct',
  aboutSub: "La plateforme de référence pour les entreprises françaises qui souhaitent développer leur activité grâce aux marchés publics, aux appels d'offres privés et à la sous-traitance.",
  aboutMissionTitle: 'Notre mission',
  aboutMissionText: "Rendre l'accès aux marchés publics, aux appels d'offres privés et à la sous-traitance aussi simple et efficace que possible pour toutes les entreprises françaises, quelle que soit leur taille.",
  aboutVisionTitle: 'Notre vision',
  aboutVisionText: "Un écosystème où chaque entreprise peut trouver, préparer et remporter des marchés grâce à l'intelligence artificielle et à l'expertise humaine, sans expertise administrative préalable.",
  aboutApproachTitle: 'Notre approche',
  aboutApproachText: "Nous combinons surveillance automatique des sources (BOAMP, PLACE, JOUE, sources privées), qualification par IA et accompagnement humain pour offrir une solution complète de A à Z.",
  aboutTeamTitle: 'Notre équipe',
  aboutSeeAll: 'Voir tous',
  aboutWhyTitle: 'Pourquoi Marchés Direct ?',
  aboutReason1: 'Couverture complète : marchés publics, privés et sous-traitance',
  aboutReason2: 'IA entraînée sur des milliers de marchés français',
  aboutReason3: 'Génération automatique des pièces administratives',
  aboutReason4: 'Équipe de conseillers spécialisés en commande publique',
  aboutReason5: 'Tarifs adaptés aux PME et TPE',
  aboutReason6: 'Résultats mesurables : + 40 % de dossiers déposés en moyenne',
  aboutCta1: 'Comment ça marche',
  aboutCta2: 'Notre équipe',

  // Équipe Page
  teamTag: 'Notre équipe',
  teamTitle: 'Rencontrez nos experts.',
  teamSub: "Une équipe engagée, expérimentée et spécialisée dans la veille et la réponse aux appels d'offres privés, aux marchés publics et aux opportunités de sous-traitance.",

  // Actualités Page
  newsPageTag: 'Actualités',
  newsPageTitle: "L'actualité des marchés.",
  newsPageSub: 'Réglementation, nouvelles opportunités et secteurs à suivre.',
  newsCat1: 'Tous',
  newsCat2: 'Réglementation',
  newsCat3: 'Tendances',
  newsCat4: 'Opportunités',

  // Secteurs Page
  sectorsPageTag: "Secteurs d'activité",
  sectorsPageTitle: 'Des opportunités pour tous les métiers',
  sectorsPageSub: "Marchés Direct couvre l'ensemble des secteurs de la commande publique et privée.",
  sectorsSeeOpp: 'Voir les opportunités',

  // FAQ Page
  faqTag: 'Questions fréquentes',
  faqTitle: 'Tout savoir avant de démarrer.',
  faqSub: "Les réponses aux principales questions avant de nous confier votre prochain marché.",

  // International Page
  intlTag: 'Explorer',
  intlTitle: "Opportunités à l'international",
  intlSub: "Marchés Direct suit les appels d'offres européens et internationaux accessibles aux entreprises françaises.",
  intlSelect: 'Sélectionnez un marché',
  intlSelectSub: 'Cliquez sur un pays ou une zone pour découvrir les opportunités disponibles.',
  intlOpp: 'opp.',
  intlKeywords: 'Mots-clés',
  intlExplore: 'Explorer',
  intlAvailable: 'opportunités disponibles',
  intlEU: 'Union européenne',
  intlEUSub: 'JOUE + TED',
  intlEUDesc: "Appels d'offres publiés au Journal officiel de l'UE (TED/JOUE) accessibles aux entreprises françaises.",
  intlBelgium: 'Belgique',
  intlBelgiumSub: 'Marchés fédéraux et régionaux',
  intlBelgiumDesc: 'Marchés publics belges ouverts aux prestataires étrangers, notamment en Wallonie et à Bruxelles.',
  intlLux: 'Luxembourg',
  intlLuxSub: "Appels d'offres publics",
  intlLuxDesc: "Petite économie très active avec des appels d'offres récurrents dans les services et la construction.",
  intlSwiss: 'Suisse',
  intlSwissSub: 'Simap + cantons',
  intlSwissDesc: 'Marchés fédéraux et cantonaux accessibles via la plateforme Simap pour les entreprises francophones.',
  intlSpain: 'Espagne',
  intlSpainSub: 'PLACSP',
  intlSpainDesc: "Marchés publiés sur la Plateforme de Contratación del Sector Público, en fort développement.",
  intlGermany: 'Allemagne',
  intlGermanySub: 'DTVP + Vergabe24',
  intlGermanyDesc: 'Marchés Länder et fédéraux via les plateformes allemandes. Fort volume, tous secteurs représentés.',
  intlOther: 'Autres marchés',
  intlOtherSub: 'International élargi',
  intlOtherDesc: "Marchés d'organisations internationales, bailleurs de fonds (BM, AFD, BERD) et autres pays européens.",

  // Mentions Légales
  legalTitle: 'Mentions légales',
  legalPublisher: 'Éditeur',
  legalHost: 'Hébergeur',
  legalContactInfo: 'Coordonnées',
  legalIP: 'Propriété intellectuelle',
  legalResponsibility: 'Responsabilité',
  legalPublisherContent: ['Marchés Direct SAS', 'Capital social : 50 000 €', 'RCS Paris B 987 654 321', 'Siège social : 15 rue de la Paix, 75001 Paris, France', 'Directeur de la publication : Jean Dupont'],
  legalHostContent: ['Supabase Inc.', '970 Toa Payoh North, Singapore 318992', 'https://supabase.com'],
  legalContactContent: ['Email : contact@marchesdirect.fr', 'Téléphone : +33 1 23 45 67 89', 'Horaires : Lundi – Vendredi, 9h – 18h'],
  legalIPContent: ["L'ensemble du contenu de ce site (textes, images, logos, structure) est protégé par le droit d'auteur et appartient à Marchés Direct SAS ou à ses partenaires.", 'Toute reproduction, même partielle, est interdite sans autorisation préalable écrite.'],
  legalResponsibilityContent: ["Marchés Direct s'efforce de maintenir les informations disponibles à jour et exactes. Toutefois, la société ne saurait être tenue responsable des erreurs ou omissions dans les contenus publiés.", "L'utilisation des informations disponibles sur ce site se fait sous la responsabilité exclusive de l'utilisateur."],

  // Confidentialité
  privacyTitle: 'Politique de confidentialité',
  privacyUpdated: 'Dernière mise à jour : 1er août 2026',
  privacyData: 'Données collectées',
  privacyDataText: "Marchés Direct collecte les données nécessaires à la fourniture de ses services : nom, prénom, adresse email, numéro de téléphone, SIRET de l'entreprise, adresse postale et préférences de recherche. Ces données sont collectées lors de l'inscription et lors de l'utilisation du service.",
  privacyPurpose: 'Finalités du traitement',
  privacyPurposeText: "Vos données sont utilisées pour : créer et gérer votre compte, vous envoyer des alertes d'opportunités, générer vos dossiers de réponse, améliorer nos services grâce à des statistiques anonymisées, et vous contacter dans le cadre du support client.",
  privacyRetention: 'Conservation des données',
  privacyRetentionText: "Vos données sont conservées pendant la durée de votre abonnement et jusqu'à 3 ans après la résiliation de votre compte, sauf obligation légale de conservation plus longue. Les données de facturation sont conservées 10 ans conformément aux obligations comptables.",
  privacyRights: 'Vos droits (RGPD)',
  privacyRightsText: "Conformément au RGPD et à la loi Informatique et Libertés, vous disposez d'un droit d'accès, de rectification, d'effacement, de limitation, de portabilité et d'opposition. Pour exercer ces droits, contactez : privacy@marchesdirect.fr",
  privacyDelete: 'Suppression du compte',
  privacyDeleteText: "Vous pouvez demander la suppression de votre compte et de vos données à tout moment depuis votre espace Profil > Application, ou en nous contactant directement. La suppression est effective sous 30 jours ouvrés.",
  privacySecurity: 'Sécurité',
  privacySecurityText: "Marchés Direct met en œuvre des mesures techniques et organisationnelles adaptées pour protéger vos données : chiffrement en transit (TLS), chiffrement au repos, authentification à deux facteurs disponible, audit de sécurité régulier et hébergement conforme ISO 27001.",
  privacyCookies: 'Cookies',
  privacyCookiesText: "Nous utilisons des cookies strictement nécessaires au fonctionnement du service (session, préférences) et des cookies analytiques anonymisés pour améliorer l'expérience. Aucun cookie publicitaire tiers n'est utilisé.",
  privacyDpo: "Pour toute question relative à vos données personnelles, contactez notre DPO :",

  // CGU
  cguTitle: "Conditions Générales d'Utilisation",
  cguUpdated: 'Version en vigueur depuis le 1er janvier 2026',
  cguService: 'Utilisation du service',
  cguServiceText: "Marchés Direct est une plateforme de veille, de qualification et d'assistance à la réponse aux appels d'offres. L'accès au service est réservé aux professionnels (entreprises, auto-entrepreneurs, associations). L'utilisation à des fins personnelles ou non commerciales n'est pas autorisée.",
  cguAccount: 'Création de compte',
  cguAccountText: "L'inscription requiert la fourniture d'informations exactes et à jour. Vous êtes seul responsable de la confidentialité de vos identifiants. Tout accès non autorisé à votre compte doit être signalé immédiatement à Marchés Direct.",
  cguSubscriptions: 'Abonnements',
  cguSubscriptionsText: "Les abonnements sont payants (sauf Découverte). Le paiement s'effectue mensuellement par prélèvement automatique. Les tarifs sont affichés HT. Marchés Direct se réserve le droit de modifier ses tarifs avec un préavis de 30 jours.",
  cguCancellation: 'Résiliation',
  cguCancellationText: "Vous pouvez résilier votre abonnement à tout moment depuis votre espace Profil. La résiliation prend effet à la fin de la période en cours. Aucun remboursement prorata temporis n'est effectué sauf cas prévu par la loi.",
  cguModule: "Module réponse aux appels d'offres",
  cguModuleText: "La génération de dossiers par IA est fournie à titre d'assistance uniquement. Marchés Direct ne garantit pas l'attribution des marchés. Les dossiers générés doivent être vérifiés et validés par l'utilisateur avant soumission. La responsabilité du contenu déposé incombe à l'utilisateur.",
  cguLiability: 'Responsabilités',
  cguLiabilityText: "Marchés Direct s'engage à assurer la disponibilité du service (SLA 99,5 % hors maintenance planifiée) et à sécuriser les données. En cas d'indisponibilité prolongée, une proratisation de l'abonnement peut être accordée sur demande. Marchés Direct n'est pas responsable des décisions des acheteurs publics ou privés.",
  cguLaw: 'Loi applicable',
  cguLawText: "Les présentes CGU sont soumises au droit français. Tout litige sera de la compétence exclusive des tribunaux de Paris, sauf disposition légale contraire.",

  // Contact Page
  contactTag: 'Contactez-nous',
  contactTitle: 'Comment pouvons-nous vous aider ?',
  contactSub: 'Choisissez le canal le plus adapté à votre besoin.',
  contactRdv: 'Prendre rendez‑vous',
  contactRdvSub: 'Planifiez un entretien avec un conseiller.',
  contactCallback: 'Être rappelé',
  contactCallbackSub: 'Un conseiller vous rappelle sous 24h.',
  contactMessage: 'Nous écrire',
  contactMessageSub: 'Envoyez-nous un message directement.',
  contactName: 'Nom *',
  contactNamePlaceholder: 'Votre nom complet',
  contactCompany: 'Entreprise',
  contactCompanyPlaceholder: 'Nom de votre entreprise',
  contactEmail: 'Email *',
  contactEmailPlaceholder: 'vous@exemple.fr',
  contactPhone: 'Téléphone',
  contactPhonePlaceholder: '06 xx xx xx xx',
  contactSubject: 'Sujet *',
  contactMessageLabel: 'Message *',
  contactMessagePlaceholder: 'Décrivez votre demande...',
  contactSubmit: 'Envoyer le message',
  contactSentTitle: 'Message envoyé !',
  contactSentSub: 'Nous vous répondrons dans les meilleurs délais, généralement sous 24h ouvrées.',
  contactSentAgain: 'Envoyer un autre message',
  contactSubj1: "Demande d'information",
  contactSubj2: 'Problème technique',
  contactSubj3: 'Question sur mon abonnement',
  contactSubj4: 'Partenariat',
  contactSubj5: 'Autre',

  // Dashboard Keys
  dashWelcome: 'Bonjour',
  dashUserName: 'Jean Dupont',
  dashOverview: "Vue d'ensemble",
  dashRecommended: 'Recommandées',
  dashSaved: 'Sauvegardées',
  dashDossiers: 'Mes dossiers',
  dashDeadlines: 'Échéances',
  dashNotifications: 'Notifications',
  dashMyProfile: 'Mon profil',
  dashOpportunitiesRecommended: 'Opportunités recommandées',
  dashDossiersInProgress: 'Dossiers en cours',
  dashMatchingRate: 'Taux de matching moyen',
  dashValidDocuments: 'Documents valides',
  dashStatsLoadError: 'Impossible de charger les statistiques. Réessayez plus tard.',
  dashUnreadAlerts: 'Alertes non lues',
  dashViewAll: 'Voir tout',
  dashUrgent: 'Urgent',
  dashRecentActivity: 'Activité récente',
  dashRecommendedOpps: 'Opportunités recommandées',
  
  // Step 1
  step1Label: 'Opportunité',
  step2Label: 'Analyse',
  step3Label: 'Préparation',
  step4Label: 'Validation',
  dashMarchPublic: 'Marché public',
  dashNew: 'Nouveau',
  dashHighCompatibility: 'Compatibilité élevée',
  dashLocation: 'Localisation',
  dashBudgetEst: 'Budget estimé',
  dashDeadlineLabel: 'Échéance',
  dashDurationEst: 'Durée estimée',
  dashSellerNeeds: 'Ce que recherche le donneur d\'ordre',
  dashWhyThisOpportunity: 'Pourquoi cette opportunité peut vous correspondre',
  dashZoneCompatible: 'Zone d’intervention compatible',
  dashActivityMatches: 'Activité correspondant à votre métier',
  dashBudgetCompatible: 'Budget adapté à votre capacité',
  dashComfortableDelay: 'Délai de réponse encore confortable',
  dashMDTakesCare: 'Marchés Direct s\'occupe du reste',
  dashMDTakesCareText: 'Nous analysons le dossier, préparons les documents et construisons votre réponse. Vous serez sollicité uniquement pour les informations indispensables et la validation finale.',
  dashViewDocs: 'Consulter les documents originaux',
  dashInterested: 'Cette opportunité m\'intéresse',
  dashSaveForLater: 'Enregistrer pour plus tard',

  // Step 2
  dashAnalyseMDF: 'Analyse Marchés Direct',
  dashRecommendedTitle: 'Cette opportunité est recommandée.',
  dashRecommendedSub: 'Votre entreprise présente les principaux critères recherchés par le donneur d’ordre.',
  dashOpportunityRecommended: 'Opportunité recommandée',
  dashCriteria1: 'Votre métier correspond aux prestations',
  dashCriteria2: 'Votre zone d’intervention est compatible',
  dashCriteria3: 'Vos références peuvent valoriser la candidature',
  dashCriteria4: 'Le calendrier permet de préparer une réponse solide',
  dashMDPrepares: 'Ce que Marchés Direct va préparer',
  dashPrep1: 'Analyse complète du marché',
  dashPrep2: 'Documents administratifs',
  dashPrep3: 'Mémoire technique personnalisé',
  dashPrep4: 'Structure du bordereau de prix',
  dashPrep5: 'Contrôle final et dépôt',
  dashLimitedIntervention: 'Votre intervention sera limitée',
  dashLimitedInterventionText: 'Nous vous demanderons uniquement les informations manquantes, la validation de vos prix et votre accord final avant le dépôt.',
  dashEntrust: 'Confier ma candidature à Marchés Direct',
  dashTalkToAdvisor: 'Je souhaite parler à un conseiller',

  // Step 3
  dashPreparationTitle: 'Marchés Direct prépare votre dossier.',
  dashPreparationSub: 'Suivez simplement l’avancement. Nous vous contactons uniquement lorsqu’une action est nécessaire.',
  dashStep1Analysis: 'Analyse du marché',
  dashStep2Docs: 'Documents administratifs',
  dashStep3Memo: 'Mémoire technique personnalisé',
  dashStep4Prices: 'Bordereau de prix',
  dashStep5Control: 'Contrôle final et dépôt',
  dashStatusDone: 'Terminée',
  dashStatusPrepared: 'Préparés',
  dashStatusInProgress: 'En cours de préparation',
  dashStatusWaitingInfo: 'En attente de vos informations',
  dashStatusUpcoming: 'À venir',
  dashDossierProgress: 'Dossier préparé à',
  dashActionNeeded: 'Une action est nécessaire',
  dashActionNeededText: 'Indiquez-nous vos prix pour finaliser la candidature.',
  dashSubmitPrices: 'Transmettre mes prix',
  dashEstimatedTime: 'Temps estimé : 5 minutes',
  dashYourAdvisor: 'Votre conseiller',
  dashContactAdvisor: 'Contacter ma conseillère',
  dashNoDocsNeeded: 'Vous n\'avez aucun document technique à télécharger. Marchés Direct s\'occupe de la préparation.',
  dashSeeFinalValidation: 'Voir la validation finale',
  dashBackToAnalysis: 'Revenir à l\'analyse',

  // Step 4
  dashFinalValidation: 'Validation finale',
  dashReady: 'Votre candidature est prête.',
  dashReadySub: 'Marchés Direct a préparé et vérifié votre dossier. Il ne reste plus qu’à valider les derniers éléments.',
  dashDossierReady: 'Dossier prêt',
  dashCheck1: 'Documents administratifs vérifiés',
  dashCheck2: 'Mémoire technique finalisé',
  dashCheck3: 'Prix renseignés et contrôlés',
  dashCheck4: 'Dossier conforme au format demandé',
  dashCheck5: 'Date limite respectée',
  dashDepositBefore: 'Dépôt prévu avant le 24 août 2026',
  dashYourValidation: 'Votre validation',
  dashConfirm1: 'Je confirme les informations de mon entreprise',
  dashConfirm2: 'Je valide les prix présentés',
  dashConfirm3: 'J’autorise Marchés Direct à déposer la candidature',
  dashAfterAuthorization: 'Après votre autorisation',
  dashAfterAuthorizationText: 'Marchés Direct transmettra le dossier sur la plateforme du donneur d\'ordre. Vous recevrez une confirmation de dépôt dans votre tableau de bord.',
  dashValidateDeposit: 'Valider et autoriser le dépôt',
  dashRequestModification: 'Demander une dernière modification',
  dashFinalDecision: 'Vous conservez la décision finale. Aucun dossier n\'est déposé sans votre accord.',

  // Profile Page
  profileTitle: 'Mon profil entreprise',
  profileAccessDiscovery: 'Accès Découverte',
  profileCompanyName: 'BâtiNova',
  profileUserName: 'Julien Martin',
  profileCompletion: 'Profil complété à 60 %',
  profileCompleteProfile: 'Compléter mon profil',
  profileContactInfo: 'Coordonnées',
  profileEdit: 'Modifier',
  profileActivityZones: 'Activité et zones',
  profileActivities: 'Gros œuvre',
  profileRenovation: 'Rénovation',
  profileRegion: 'Pays de la Loire',
  profileRadius: 'Rayon',
  profileDocsToComplete: 'Dossier entreprise à compléter',
  profileKbis: 'Kbis',
  profileInsurance: 'Assurance RC Pro / décennale',
  profileCertifications: 'Qualifications / certifications',
  profileSiteRefs: 'Références de chantiers',
  profileActivateFullAccess: 'Activez votre accès complet',
  profileFullAccessText: "Un chargé d'affaires vérifie votre profil et vous présente par téléphone l'accompagnement adapté à votre entreprise.",
  profileCallMeBack: 'Être rappelé par un conseiller',

  // Admin Keys
  adminDashboard: 'Tableau de bord admin',
  adminWelcomeBack: 'Bienvenue dans votre espace d\'administration',
  adminTenders: 'Gestion des marchés',
  adminManageTenders: 'Gérez tous les appels d\'offres de la plateforme',
  adminUsers: 'Gestion des utilisateurs',
  adminManageUsers: 'Gérez les comptes et les abonnements',
  adminLeads: 'Demandes d\'accès',
  adminManageLeads: 'Coordonnées laissées sur une fiche opportunité, en attente de validation',
  adminSubscriptions: 'Abonnements',
  adminBrands: 'Marques',
  adminSettings: 'Paramètres',
  adminSettingsDesc: 'Configuration générale de la plateforme',
  adminSearchPlaceholder: 'Rechercher dans l\'admin...',
  adminRecentActivity: 'Activité récente',
  adminStatsTenders: 'Marchés actifs',
  adminStatsUsers: 'Utilisateurs inscrits',
  adminStatsMatches: 'Taux de matching',
  adminStatsRevenue: 'Revenus mensuels',
  adminAddTender: 'Ajouter un marché',
  adminAddUser: 'Ajouter un utilisateur',
  adminSearchTenders: 'Rechercher un marché...',
  adminSearchUsers: 'Rechercher un utilisateur...',
  adminAllStatuses: 'Tous les statuts',
  adminActive: 'Actif',
  adminPending: 'En attente',
  adminClosed: 'Clôturé',
  adminTitle: 'Titre',
  adminBuyer: 'Acheteur',
  adminBudget: 'Budget',
  adminDeadline: 'Échéance',
  adminStatus: 'Statut',
  adminName: 'Nom',
  adminCompany: 'Entreprise',
  adminEmail: 'Email',
  adminPlan: 'Formule',
  adminNoResults: 'Aucun résultat trouvé',
  adminStatus_active: 'Actif',
  adminStatus_pending: 'En attente',
  adminStatus_closed: 'Clôturé',
  adminStatus_suspended: 'Suspendu',
  backToSite: 'Retour au site',
  adminGeneral: 'Général',
  adminSiteName: 'Nom du site',
  adminSupportEmail: 'Email de support',
  adminSecurity: 'Sécurité',
  adminTwoFactor: 'Authentification à deux facteurs',
  adminMaintenance: 'Mode maintenance',
  adminNotifications: 'Notifications',
  adminEmailAlerts: 'Alertes par email',
  adminSaveChanges: 'Enregistrer les modifications',
  adminSaved: 'Modifications enregistrées !',
  adminDataSources: 'Sources de données',
  adminDataSourcesDesc: 'Connecteurs qui alimentent les annonces (BOAMP, PLACE, TED). Le cycle automatique tourne toutes les 2h - utilisez "Exécuter maintenant" pour ne pas attendre.',
  adminRunNow: 'Exécuter maintenant',
  adminRunning: 'Exécution...',
  adminRunSuccess: 'Exécution terminée',
  adminRunFailed: "Échec de l'exécution",
  adminLastRun: 'Dernière exécution',
  adminNextRun: 'Prochaine',
  adminSourceInactive: 'Inactif',
  adminView: 'Voir',
  adminEdit: 'Modifier',
  adminDelete: 'Supprimer',
  adminViewAll: 'Voir tout',
  adminSuspend: 'Suspendre',
  adminActivate: 'Activer',

  // Annonce detail page (Tenders & Marchés publics)
  detailBack: 'Retour aux résultats',
  detailNotFound: 'Cette annonce est introuvable ou a été retirée.',
  detailLoadError: "Impossible de charger cette annonce. Vérifiez votre connexion et réessayez.",
  detailPublished: 'Publiée le',
  detailDeadline: 'Date limite de remise des plis',
  detailBudget: 'Montant estimé',
  detailLocation: 'Lieu d\'exécution',
  detailTrade: 'Métier',
  detailStatus: 'Statut',
  detailDescriptionTitle: 'Description',
  detailAiSummaryTitle: 'Résumé IA',
  detailAiSummaryPending: "Cette annonce n'a pas encore été analysée par l'IA.",
  detailMatchedTradesTitle: 'Métiers correspondants (IA)',
  detailSave: 'Mettre de côté',
  detailSaved: 'Dans ma sélection',
  detailSaveLoginRequired: 'Connectez-vous pour sauvegarder cette annonce',
  detailDocumentsTitle: 'Documents',
  detailDocumentsNote: "Le dossier de consultation complet (DCE) sera téléchargeable directement ici une fois le module de réponse aux appels d'offres branché. En attendant, consultez la source officielle ci-dessous.",
  detailSourceLink: 'Voir sur la source officielle',
  detailSourceMissing: "Lien source non disponible pour cette annonce.",
  detailBackToTop: 'Haut de page',
};

const enTranslations: Translations = {
  home: 'Home',
  tenders: 'Tenders',
  public: 'Public Markets',
  subcontracting: 'Subcontracting',
  howItWorks: 'How it works',
  pricing: 'Pricing',
  search: 'Search',
  dashboard: 'Dashboard',
  profile: 'Profile',
  contact: 'Contact',
  heroLine1: 'Your next opportunity',
  heroLine2: 'starts here.',
  heroSub: 'Choose your path or speak with a Marchés Direct advisor.',
  bookAppointment: 'Book an appointment',
  callBack: 'Request a callback',
  whoWeAre: 'Who are we?',
  whoWeAreSub: 'An expert team by your side, until you sign your first contracts.',
  discoverUs: 'Discover Marchés Direct →',
  nearYou: 'NEAR YOU',
  opportunitiesFrance: 'Opportunities across France.',
  exploreFrance: 'Explore markets by region, department or city.',
  seeAllZones: 'See all zones',
  regions: 'Regions',
  departments: 'Departments',
  cities: 'Cities',
  mapSearchRegion: 'Search for a region',
  mapSearchDepartment: 'Search for a department or code',
  mapSearchCity: 'Search for a city',
  mapTouchRegion: 'Touch a region or zoom in on the map',
  mapTouchDepartment: 'Touch a department or zoom in on the map',
  mapTouchCity: 'Search for a city, then confirm',
  mapViewOpportunitiesIn: 'View opportunities in',
  mapViewOpportunitiesAround: 'View opportunities around',
  mapSelectPrompt: 'Select an area',
  mapSelectPromptSub: 'Touch a region, department, or search a city to see available opportunities.',
  mapOpportunitiesCount: 'opportunities',
  mapNoData: 'No opportunities recorded yet.',
  mapCitySearchButton: 'Show',
  international: 'International opportunities',
  internationalSub: 'Access markets available outside France.',
  sectors: 'Activity sectors',
  sectorsSub: 'Opportunities for every trade.',
  sectorsSub2: 'Explore sectors and access opportunities suited to your activity.',
  seeAllSectors: 'See all sectors',
  news: 'News',
  newsSub: 'Market news.',
  newsSub2: 'Regulations, new opportunities and sectors to follow.',
  seeAllNews: 'See all news',
  finalCtaHeading: 'Need help finding the right opportunity?',
  finalCtaSub: 'A Marchés Direct advisor helps you identify the path suited to your company.',
  // Footer
  copyright: '© 2026 MarchesDirect',
  legalNotice: 'Legal Notice',
  privacy: 'Privacy',
  terms: 'Terms',
  footerBrand: 'Marchés Direct', // Kept in French
  footerMarkets: 'Markets',
  footerExplore: 'Explore',
  footerLegal: 'Legal',
  footerTagline: "The matchmaking platform for public markets, private tenders and subcontracting.",
  footerAbout: 'About',
  footerTeam: 'Our team',
  footerZones: 'Geographic zones',
  footerSectors: 'Activity sectors',
  footerFaq: 'FAQ',
  // Modals
  appointmentTitle: 'Book a meeting',
  callbackTitle: 'Request a callback',
  callbackName: 'Name',
  callbackCompany: 'Company',
  callbackPhone: 'Phone',
  callbackTime: 'Preferred time',
  callbackSubmit: 'Request a callback',
  callbackConfirm: 'Your request has been sent. We will call you back shortly.',
  // Steps
  step1: 'We monitor',
  step2: 'We sort & qualify',
  step3: 'We prepare',
  step4: 'You validate',
  step5: 'We submit',
  step6: 'We support you',
  // Bottom nav labels
  navHome: 'Home',
  navSearch: 'Search',
  navDashboard: 'Dashboard',
  navProfile: 'Profile',
  
  zoneBreadcrumbHome: 'Home',
  zoneBreadcrumbSectors: 'Sectors',
  zoneBreadcrumbConstruction: 'Works & Construction',
  zoneTitleLine1: 'Works &',
  zoneTitleLine2: 'Construction',
  zoneSubLine1: 'What type of opportunity are you looking for in this sector?',
  zoneSubLine2: 'Your choice will be kept for the rest of the process.',
  zoneCardPublicTitle: 'Public Markets',
  zoneCardPublicDesc: 'Works ordered by local authorities and public institutions.',
  zoneCardPrivateTitle: 'Private Tenders',
  zoneCardPrivateDesc: 'Projects from developers, companies and private clients.',
  zoneCardSubTitle: 'Subcontracting',
  zoneCardSubDesc: 'Find a site, a mission or a partner.',
  changeSector: 'Change sector',
  selectedSectorLabel: 'Selected sector:',
  selectedSectorValue: 'Works & Construction',

  // Search Page
  searchHeaderTag: 'I am a subcontractor',
  searchHeaderTitle: 'Find worksites adapted to your company.',
  searchHeaderSub: 'Qualified subcontracting needs according to your trade, your area and your availability.',
  searchKeywords: 'Keywords',
  searchKeywordsPlaceholder: 'Ex. painting, electricity, structural work...',
  searchLocation: 'Location',
  searchLocationPlaceholder: 'City or department',
  searchRadius: 'Radius',
  searchAvailability: 'Availability',
  searchAvailabilityNow: 'Immediately',
  searchAvailability1: 'Within 1 month',
  searchAvailability3: 'Within 3 months',
  searchButton: 'Search',
  searchResults: 'compatible missions',
  searchNew: 'New',
  searchStart: 'Start',
  searchDuration: 'Duration',
  searchBudget: 'Indicative budget',
  searchCompatible: 'Compatible profile required',
  searchView: 'View mission',

  // Generic
  all: 'All',
  allF: 'All',
  sortRecent: 'Sort: Most recent',
  sortMatch: 'Sort: Best match',
  sortDeadline: 'Sort: Upcoming deadline',

  // Appels Page
  appelsTag: 'Private Markets',
  appelsTitle: 'Private Tenders',
  appelsSub: 'Developers, landlords and large companies. Direct contact and responsiveness above all.',
  appelsLocation: 'Location',
  appelsLocationPlaceholder: 'City, department...',
  appelsSector: 'Sector',
  appelsCategory: 'Category',
  appelsReset: 'Reset',
  appelsFilters: 'Filters',
  appelsResults: 'result',
  appelsResultsPlural: 'results',
  appelsNoResults: 'No results',
  appelsNoResultsSub: 'No opportunity matches these filters right now. Try expanding your radius or changing your trade.',
  appelsResetFilters: 'Reset filters',

  // Public Page
  publicTag: 'BOAMP · PLACE · JOUE',
  publicTitle: 'Public Markets',
  publicSub: 'Town halls, State, local authorities. Compliance, DCE documents and technical memo generated for you.',
  publicStatus: 'Status',
  publicResults: 'opportunity found',
  publicResultsPlural: 'opportunities found',
  publicNoResults: 'No results',
  publicNoResultsSub: 'No opportunity matches these filters right now. Try expanding your radius or changing your trade.',
  publicResetFilters: 'Reset filters',

  // Subcontracting Page
  subTag: 'Between companies',
  subTitle: 'Subcontracting',
  subSub: 'Lots to take over between construction companies. Speed and availability as a priority.',
  subModeChantier: 'I am looking for a site',
  subModePartenaire: 'I am looking for a partner',
  subDept: 'Department',
  subJob: 'Trade',
  subLocationPlaceholder: 'City...',
  subResults: 'lot available',
  subResultsPlural: 'lots available',
  subNoResults: 'No results',
  subNoResultsSub: 'No opportunity matches these filters.',
  subResetFilters: 'Reset filters',

  // Steps Page - Descriptions
  stepsTitle: "From opportunity to signature.",
  stepsSub: 'A simple, clear and supported process.',
  step1Desc: 'Our sources collect public and private opportunities.',
  step2Desc: 'Each opportunity is classified according to your activity and criteria.',
  step3Desc: 'We build the administrative and technical file.',
  step4Desc: 'You verify and adjust the elements before sending.',
  step5Desc: 'The file is sent to the concerned platform.',
  step6Desc: 'We stay by your side until the signature.',
  stepsCtaTitle: 'Need personalized support?',
  stepsCtaAbout: 'About →',
  stepsCtaTeam: 'Our team →',
  stepsCtaFaq: 'FAQ →',

  // Pricing Page
  pricingTitle: 'One subscription, all your opportunities.',
  pricingSub: 'Start for free. An advisor calls you back to set up your profile and choose the right plan.',
  pricingNote: 'All prices are excluding VAT. No commitment. Cancel at any time from your profile area.',
  planDiscoveryName: 'DISCOVERY',
  planDiscoveryPeriod: '14-day trial',
  planDiscoveryFeat1: '1 tracked trade',
  planDiscoveryFeat2: 'Email alerts',
  planDiscoveryFeat3: 'Search and filters',
  planDiscoveryFeat4: 'Email support',
  planDiscoveryCta: 'Try for free',
  planProName: 'PRO',
  planProPeriod: '/ month',
  planProBadge: 'Most popular',
  planProFeat1: 'Unlimited trades and journeys',
  planProFeat2: 'AI matching and summary',
  planProFeat3: 'AI Chatbot',
  planProFeat4: 'Tender response module',
  planProFeat5: 'Company profile and document vault',
  planProCta: 'Request a callback',
  planEntName: 'BUSINESS',
  planEntPrice: 'Custom quote',
  planEntPeriod: 'Multiple users',
  planEntFeat1: 'Multi-user accounts',
  planEntFeat2: 'Dedicated CRM export',
  planEntFeat3: 'Dedicated support',
  planEntFeat4: 'MFA and advanced roles',
  planEntCta: 'Request a callback',

  // À propos Page
  aboutTag: 'About',
  aboutTitle: 'Marchés Direct', // Kept in French
  aboutSub: "The reference platform for French companies looking to grow their business through public markets, private tenders and subcontracting.",
  aboutMissionTitle: 'Our mission',
  aboutMissionText: "To make access to public markets, private tenders and subcontracting as simple and effective as possible for all French companies, regardless of their size.",
  aboutVisionTitle: 'Our vision',
  aboutVisionText: "An ecosystem where every company can find, prepare and win contracts thanks to artificial intelligence and human expertise, without prior administrative expertise.",
  aboutApproachTitle: 'Our approach',
  aboutApproachText: "We combine automatic monitoring of sources (BOAMP, PLACE, JOUE, private sources), AI qualification and human support to offer a complete end-to-end solution.",
  aboutTeamTitle: 'Our team',
  aboutSeeAll: 'See all',
  aboutWhyTitle: 'Why Marchés Direct?',
  aboutReason1: 'Complete coverage: public, private and subcontracting markets',
  aboutReason2: 'AI trained on thousands of French markets',
  aboutReason3: 'Automatic generation of administrative documents',
  aboutReason4: 'Team of advisors specialized in public procurement',
  aboutReason5: 'Prices adapted to SMEs and VSEs',
  aboutReason6: 'Measurable results: +40% of files submitted on average',
  aboutCta1: 'How it works',
  aboutCta2: 'Our team',

  // Équipe Page
  teamTag: 'Our team',
  teamTitle: 'Meet our experts.',
  teamSub: "A committed, experienced team specialized in monitoring and responding to private tenders, public markets and subcontracting opportunities.",

  // Actualités Page
  newsPageTag: 'News',
  newsPageTitle: 'Market news.',
  newsPageSub: 'Regulations, new opportunities and sectors to follow.',
  newsCat1: 'All',
  newsCat2: 'Regulation',
  newsCat3: 'Trends',
  newsCat4: 'Opportunities',

  // Secteurs Page
  sectorsPageTag: 'Activity sectors',
  sectorsPageTitle: 'Opportunities for every trade',
  sectorsPageSub: "Marchés Direct covers all sectors of public and private procurement.",
  sectorsSeeOpp: 'See opportunities',

  // FAQ Page
  faqTag: 'FAQ',
  faqTitle: 'Everything to know before getting started.',
  faqSub: "The answers to the main questions before entrusting us with your next contract.",

  // International Page
  intlTag: 'Explore',
  intlTitle: 'International Opportunities',
  intlSub: "Marchés Direct monitors European and international tenders accessible to French companies.",
  intlSelect: 'Select a market',
  intlSelectSub: 'Click on a country or region to discover available opportunities.',
  intlOpp: 'opp.',
  intlKeywords: 'Keywords',
  intlExplore: 'Explore',
  intlAvailable: 'opportunities available',
  intlEU: 'European Union',
  intlEUSub: 'OJEU + TED',
  intlEUDesc: "Tenders published in the Official Journal of the EU (TED/OJEU) accessible to French companies.",
  intlBelgium: 'Belgium',
  intlBelgiumSub: 'Federal and regional markets',
  intlBelgiumDesc: 'Belgian public contracts open to foreign providers, particularly in Wallonia and Brussels.',
  intlLux: 'Luxembourg',
  intlLuxSub: 'Public tenders',
  intlLuxDesc: 'Very active small economy with recurring tenders in services and construction.',
  intlSwiss: 'Switzerland',
  intlSwissSub: 'Simap + Cantons',
  intlSwissDesc: 'Federal and cantonal contracts accessible via the Simap platform for French-speaking companies.',
  intlSpain: 'Spain',
  intlSpainSub: 'PLACSP',
  intlSpainDesc: "Tenders published on the Plataforma de Contratación del Sector Público, growing rapidly.",
  intlGermany: 'Germany',
  intlGermanySub: 'DTVP + Vergabe24',
  intlGermanyDesc: 'Federal and Länder contracts via German platforms. High volume, all sectors represented.',
  intlOther: 'Other markets',
  intlOtherSub: 'Extended international',
  intlOtherDesc: "Contracts from international organizations, donors (WB, AFD, EBRD) and other European countries.",

  // Mentions Légales
  legalTitle: 'Legal Notice',
  legalPublisher: 'Publisher',
  legalHost: 'Host',
  legalContactInfo: 'Contact Information',
  legalIP: 'Intellectual Property',
  legalResponsibility: 'Responsibility',
  legalPublisherContent: ['Marchés Direct SAS', 'Share capital: €50,000', 'RCS Paris B 987 654 321', 'Head office: 15 rue de la Paix, 75001 Paris, France', 'Publication Director: Jean Dupont'],
  legalHostContent: ['Supabase Inc.', '970 Toa Payoh North, Singapore 318992', 'https://supabase.com'],
  legalContactContent: ['Email: contact@marchesdirect.fr', 'Phone: +33 1 23 45 67 89', 'Hours: Monday – Friday, 9am – 6pm'],
  legalIPContent: ["The entire content of this site (texts, images, logos, structure) is protected by copyright and belongs to Marchés Direct SAS or its partners.", "Any reproduction, even partial, is prohibited without prior written authorization."],
  legalResponsibilityContent: ["Marchés Direct strives to keep the information available up to date and accurate. However, the company cannot be held responsible for errors or omissions in published content.", "The use of information available on this site is under the sole responsibility of the user."],

  // Confidentialité
  privacyTitle: 'Privacy Policy',
  privacyUpdated: 'Last updated: August 1, 2026',
  privacyData: 'Data collected',
  privacyDataText: "Marchés Direct collects the data necessary to provide its services: first name, last name, email address, phone number, company SIRET, postal address and search preferences. This data is collected during registration and during use of the service.",
  privacyPurpose: 'Purposes of processing',
  privacyPurposeText: "Your data is used to: create and manage your account, send you opportunity alerts, generate your response files, improve our services through anonymized statistics, and contact you for customer support.",
  privacyRetention: 'Data retention',
  privacyRetentionText: "Your data is kept for the duration of your subscription and up to 3 years after the cancellation of your account, unless there is a legal obligation for longer retention. Billing data is kept for 10 years in accordance with accounting obligations.",
  privacyRights: 'Your rights (GDPR)',
  privacyRightsText: "In accordance with the GDPR and the French Data Protection Act, you have the right to access, rectify, erase, restrict, portability and object. To exercise these rights, contact: privacy@marchesdirect.fr",
  privacyDelete: 'Account deletion',
  privacyDeleteText: "You can request the deletion of your account and data at any time from your Profile > Application area, or by contacting us directly. Deletion is effective within 30 working days.",
  privacySecurity: 'Security',
  privacySecurityText: "Marchés Direct implements appropriate technical and organizational measures to protect your data: encryption in transit (TLS), encryption at rest, two-factor authentication available, regular security audit and ISO 27001 compliant hosting.",
  privacyCookies: 'Cookies',
  privacyCookiesText: "We use strictly necessary cookies for the operation of the service (session, preferences) and anonymized analytical cookies to improve the experience. No third-party advertising cookies are used.",
  privacyDpo: "For any question regarding your personal data, contact our DPO:",

  // CGU
  cguTitle: "Terms and Conditions of Use",
  cguUpdated: 'Version in force since January 1, 2026',
  cguService: 'Use of the service',
  cguServiceText: "Marchés Direct is a platform for monitoring, qualifying and assisting with responses to calls for tenders. Access to the service is reserved for professionals (companies, self-employed workers, associations). Use for personal or non-commercial purposes is not authorized.",
  cguAccount: 'Account creation',
  cguAccountText: "Registration requires the provision of accurate and up-to-date information. You are solely responsible for the confidentiality of your identifiers. Any unauthorized access to your account must be reported immediately to Marchés Direct.",
  cguSubscriptions: 'Subscriptions',
  cguSubscriptionsText: "Subscriptions are paid (except Discovery). Payment is made monthly by automatic debit. Prices are shown excluding VAT. Marchés Direct reserves the right to modify its prices with 30 days' notice.",
  cguCancellation: 'Cancellation',
  cguCancellationText: "You can cancel your subscription at any time from your Profile area. Cancellation takes effect at the end of the current period. No pro-rata refund is made except as provided by law.",
  cguModule: "Tender response module",
  cguModuleText: "AI file generation is provided for assistance only. Marchés Direct does not guarantee the award of contracts. Generated files must be verified and validated by the user before submission. Responsibility for submitted content lies with the user.",
  cguLiability: 'Responsibilities',
  cguLiabilityText: "Marchés Direct undertakes to ensure the availability of the service (99.5% SLA excluding scheduled maintenance) and to secure data. In the event of prolonged unavailability, a pro-rata reduction of the subscription may be granted on request. Marchés Direct is not responsible for the decisions of public or private buyers.",
  cguLaw: 'Applicable law',
  cguLawText: "These Terms are subject to French law. Any dispute will be under the exclusive jurisdiction of the courts of Paris, unless otherwise provided by law.",

  // Contact Page
  contactTag: 'Contact us',
  contactTitle: 'How can we help you?',
  contactSub: 'Choose the channel best suited to your needs.',
  contactRdv: 'Book an appointment',
  contactRdvSub: 'Schedule an interview with an advisor.',
  contactCallback: 'Request a callback',
  contactCallbackSub: 'An advisor calls you back within 24 hours.',
  contactMessage: 'Write to us',
  contactMessageSub: 'Send us a message directly.',
  contactName: 'Name *',
  contactNamePlaceholder: 'Your full name',
  contactCompany: 'Company',
  contactCompanyPlaceholder: 'Your company name',
  contactEmail: 'Email *',
  contactEmailPlaceholder: 'you@example.com',
  contactPhone: 'Phone',
  contactPhonePlaceholder: '06 xx xx xx xx',
  contactSubject: 'Subject *',
  contactMessageLabel: 'Message *',
  contactMessagePlaceholder: 'Describe your request...',
  contactSubmit: 'Send message',
  contactSentTitle: 'Message sent!',
  contactSentSub: 'We will get back to you as soon as possible, usually within 24 working hours.',
  contactSentAgain: 'Send another message',
  contactSubj1: 'Information request',
  contactSubj2: 'Technical issue',
  contactSubj3: 'Question about my subscription',
  contactSubj4: 'Partnership',
  contactSubj5: 'Other',

  // Dashboard Keys
  dashWelcome: 'Hello',
  dashUserName: 'Jean Dupont',
  dashOverview: 'Overview',
  dashRecommended: 'Recommended',
  dashSaved: 'Saved',
  dashDossiers: 'My files',
  dashDeadlines: 'Deadlines',
  dashNotifications: 'Notifications',
  dashMyProfile: 'My profile',
  dashOpportunitiesRecommended: 'Recommended opportunities',
  dashDossiersInProgress: 'Files in progress',
  dashMatchingRate: 'Average matching rate',
  dashValidDocuments: 'Valid documents',
  dashStatsLoadError: 'Unable to load statistics. Please try again later.',
  dashUnreadAlerts: 'Unread alerts',
  dashViewAll: 'View all',
  dashUrgent: 'Urgent',
  dashRecentActivity: 'Recent activity',
  dashRecommendedOpps: 'Recommended opportunities',
  
  // Step 1
  step1Label: 'Opportunity',
  step2Label: 'Analysis',
  step3Label: 'Preparation',
  step4Label: 'Validation',
  dashMarchPublic: 'Public contract',
  dashNew: 'New',
  dashHighCompatibility: 'High compatibility',
  dashLocation: 'Location',
  dashBudgetEst: 'Estimated budget',
  dashDeadlineLabel: 'Deadline',
  dashDurationEst: 'Estimated duration',
  dashSellerNeeds: 'What the buyer is looking for',
  dashWhyThisOpportunity: 'Why this opportunity could be right for you',
  dashZoneCompatible: 'Compatible intervention area',
  dashActivityMatches: 'Activity matching your trade',
  dashBudgetCompatible: 'Budget adapted to your capacity',
  dashComfortableDelay: 'Response deadline still comfortable',
  dashMDTakesCare: 'Marchés Direct takes care of the rest',
  dashMDTakesCareText: 'We analyze the file, prepare the documents and build your response. You will only be asked for essential information and final validation.',
  dashViewDocs: 'View original documents',
  dashInterested: 'I am interested in this opportunity',
  dashSaveForLater: 'Save for later',

  // Step 2
  dashAnalyseMDF: 'Marchés Direct Analysis',
  dashRecommendedTitle: 'This opportunity is recommended.',
  dashRecommendedSub: 'Your company meets the main criteria requested by the buyer.',
  dashOpportunityRecommended: 'Recommended opportunity',
  dashCriteria1: 'Your trade matches the services',
  dashCriteria2: 'Your intervention area is compatible',
  dashCriteria3: 'Your references can enhance your application',
  dashCriteria4: 'The schedule allows for a solid response',
  dashMDPrepares: 'What Marchés Direct will prepare',
  dashPrep1: 'Complete market analysis',
  dashPrep2: 'Administrative documents',
  dashPrep3: 'Personalized technical memo',
  dashPrep4: 'Price schedule structure',
  dashPrep5: 'Final review and submission',
  dashLimitedIntervention: 'Your involvement will be limited',
  dashLimitedInterventionText: 'We will only ask for missing information, validation of your prices and final approval before submission.',
  dashEntrust: 'Entrust my application to Marchés Direct',
  dashTalkToAdvisor: 'I want to speak with an advisor',

  // Step 3
  dashPreparationTitle: 'Marchés Direct is preparing your file.',
  dashPreparationSub: 'Simply track the progress. We only contact you when action is needed.',
  dashStep1Analysis: 'Market analysis',
  dashStep2Docs: 'Administrative documents',
  dashStep3Memo: 'Personalized technical memo',
  dashStep4Prices: 'Price schedule',
  dashStep5Control: 'Final review and submission',
  dashStatusDone: 'Completed',
  dashStatusPrepared: 'Prepared',
  dashStatusInProgress: 'In preparation',
  dashStatusWaitingInfo: 'Waiting for your information',
  dashStatusUpcoming: 'Upcoming',
  dashDossierProgress: 'File prepared at',
  dashActionNeeded: 'Action needed',
  dashActionNeededText: 'Provide your prices to finalize the application.',
  dashSubmitPrices: 'Submit my prices',
  dashEstimatedTime: 'Estimated time: 5 minutes',
  dashYourAdvisor: 'Your advisor',
  dashContactAdvisor: 'Contact my advisor',
  dashNoDocsNeeded: 'You do not need to upload any technical documents. Marchés Direct handles the preparation.',
  dashSeeFinalValidation: 'See final validation',
  dashBackToAnalysis: 'Back to analysis',

  // Step 4
  dashFinalValidation: 'Final validation',
  dashReady: 'Your application is ready.',
  dashReadySub: 'Marchés Direct has prepared and checked your file. Only the final items remain.',
  dashDossierReady: 'File ready',
  dashCheck1: 'Administrative documents verified',
  dashCheck2: 'Technical memo finalized',
  dashCheck3: 'Prices provided and reviewed',
  dashCheck4: 'File compliant with requested format',
  dashCheck5: 'Deadline respected',
  dashDepositBefore: 'Submission planned before August 24, 2026',
  dashYourValidation: 'Your validation',
  dashConfirm1: 'I confirm my company information',
  dashConfirm2: 'I validate the submitted prices',
  dashConfirm3: 'I authorize Marchés Direct to submit the application',
  dashAfterAuthorization: 'After your authorization',
  dashAfterAuthorizationText: 'Marchés Direct will submit the file on the buyer’s platform. You will receive a submission confirmation in your dashboard.',
  dashValidateDeposit: 'Validate and authorize submission',
  dashRequestModification: 'Request a final modification',
  dashFinalDecision: 'You keep the final decision. No file is submitted without your consent.',

  // Profile Page
  profileTitle: 'My business profile',
  profileAccessDiscovery: 'Discovery access',
  profileCompanyName: 'BâtiNova',
  profileUserName: 'Julien Martin',
  profileCompletion: 'Profile 60% completed',
  profileCompleteProfile: 'Complete my profile',
  profileContactInfo: 'Contact information',
  profileEdit: 'Edit',
  profileActivityZones: 'Activity and zones',
  profileActivities: 'Structural work',
  profileRenovation: 'Renovation',
  profileRegion: 'Pays de la Loire',
  profileRadius: 'Radius',
  profileDocsToComplete: 'Company file to complete',
  profileKbis: 'Kbis',
  profileInsurance: 'Professional liability / decennial insurance',
  profileCertifications: 'Qualifications / certifications',
  profileSiteRefs: 'Site references',
  profileActivateFullAccess: 'Activate your full access',
  profileFullAccessText: "A business manager checks your profile and presents the support adapted to your company over the phone.",
  profileCallMeBack: 'Request a callback from an advisor',

  // Admin Keys
  adminDashboard: 'Admin Dashboard',
  adminWelcomeBack: 'Welcome to your admin space',
  adminTenders: 'Tender Management',
  adminManageTenders: 'Manage all tenders on the platform',
  adminUsers: 'User Management',
  adminManageUsers: 'Manage accounts and subscriptions',
  adminLeads: 'Access requests',
  adminManageLeads: 'Contact details left on an opportunity page, pending review',
  adminSubscriptions: 'Subscriptions',
  adminBrands: 'Brands',
  adminSettings: 'Settings',
  adminSettingsDesc: 'General platform configuration',
  adminSearchPlaceholder: 'Search in admin...',
  adminRecentActivity: 'Recent Activity',
  adminStatsTenders: 'Active Tenders',
  adminStatsUsers: 'Registered Users',
  adminStatsMatches: 'Matching Rate',
  adminStatsRevenue: 'Monthly Revenue',
  adminAddTender: 'Add Tender',
  adminAddUser: 'Add User',
  adminSearchTenders: 'Search tender...',
  adminSearchUsers: 'Search user...',
  adminAllStatuses: 'All statuses',
  adminActive: 'Active',
  adminPending: 'Pending',
  adminClosed: 'Closed',
  adminTitle: 'Title',
  adminBuyer: 'Buyer',
  adminBudget: 'Budget',
  adminDeadline: 'Deadline',
  adminStatus: 'Status',
  adminName: 'Name',
  adminCompany: 'Company',
  adminEmail: 'Email',
  adminPlan: 'Plan',
  adminNoResults: 'No results found',
  adminStatus_active: 'Active',
  adminStatus_pending: 'Pending',
  adminStatus_closed: 'Closed',
  adminStatus_suspended: 'Suspended',
  backToSite: 'Back to site',
  adminGeneral: 'General',
  adminSiteName: 'Site Name',
  adminSupportEmail: 'Support Email',
  adminSecurity: 'Security',
  adminTwoFactor: 'Two-Factor Authentication',
  adminMaintenance: 'Maintenance Mode',
  adminNotifications: 'Notifications',
  adminEmailAlerts: 'Email Alerts',
  adminSaveChanges: 'Save Changes',
  adminSaved: 'Changes saved!',
  adminDataSources: 'Data Sources',
  adminDataSourcesDesc: 'Connectors that feed listings in (BOAMP, PLACE, TED). The automatic cycle runs every 2h - use "Run now" to skip the wait.',
  adminRunNow: 'Run now',
  adminRunning: 'Running...',
  adminRunSuccess: 'Run complete',
  adminRunFailed: 'Run failed',
  adminLastRun: 'Last run',
  adminNextRun: 'Next run',
  adminSourceInactive: 'Inactive',
  adminView: 'View',
  adminEdit: 'Edit',
  adminDelete: 'Delete',
  adminViewAll: 'View all',
  adminSuspend: 'Suspend',
  adminActivate: 'Activate',

  // Annonce detail page (Tenders & Marchés publics)
  detailBack: 'Back to results',
  detailNotFound: 'This listing could not be found or has been withdrawn.',
  detailLoadError: 'Could not load this listing. Check your connection and try again.',
  detailPublished: 'Published on',
  detailDeadline: 'Submission deadline',
  detailBudget: 'Estimated amount',
  detailLocation: 'Place of performance',
  detailTrade: 'Trade',
  detailStatus: 'Status',
  detailDescriptionTitle: 'Description',
  detailAiSummaryTitle: 'AI summary',
  detailAiSummaryPending: 'This listing has not been analyzed by the AI yet.',
  detailMatchedTradesTitle: 'Matched trades (AI)',
  detailSave: 'Save',
  detailSaved: 'In your selection',
  detailSaveLoginRequired: 'Log in to save this listing',
  detailDocumentsTitle: 'Documents',
  detailDocumentsNote: "The full tender document package (DCE) will be downloadable directly here once the tender-response module is wired up. In the meantime, check the official source below.",
  detailSourceLink: 'View on the official source',
  detailSourceMissing: 'No source link available for this listing.',
  detailBackToTop: 'Back to top',
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
  // For the handful of translation entries that are genuinely multi-paragraph
  // arrays (legal pages) rather than a single string - t() always collapses
  // these to a joined string so every other `{t('x')}` call site in the app
  // keeps working unchanged; use tList() specifically where each paragraph
  // needs to render as its own element (see MentionsLegalesPage).
  tList: (key: string) => string[];
}

const LangContext = createContext<LangContextType>({
  lang: 'en',
  setLang: () => {},
  t: (k) => k,
  tList: (k) => [k],
});

export function LangProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>('en');

  const t = (key: string): string => {
    const dict = lang === 'fr' ? frTranslations : enTranslations;
    const value = dict[key] ?? key;
    return Array.isArray(value) ? value.join(' ') : value;
  };

  const tList = (key: string): string[] => {
    const dict = lang === 'fr' ? frTranslations : enTranslations;
    const value = dict[key] ?? key;
    return Array.isArray(value) ? value : [value];
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t, tList }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);